//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmueblesCrud.BusinessEntities.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InmueblesCrud.BusinessEntities.ViewModels.ErrorDescription", typeof(ErrorDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación realizada con éxito.
        /// </summary>
        public static string _0000 {
            get {
                return ResourceManager.GetString("0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el objeto {0} a ser procesado {1}.
        /// </summary>
        public static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no puede estar vacío.
        /// </summary>
        public static string _4001 {
            get {
                return ResourceManager.GetString("4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe enviar al menos uno de los siguientes campos: {0}.
        /// </summary>
        public static string _4002 {
            get {
                return ResourceManager.GetString("4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} solo permite los valores: {1}.
        /// </summary>
        public static string _4003 {
            get {
                return ResourceManager.GetString("4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} solo permite valores positivos mayores a 0.
        /// </summary>
        public static string _4004 {
            get {
                return ResourceManager.GetString("4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe tener el formato {1}.
        /// </summary>
        public static string _4005 {
            get {
                return ResourceManager.GetString("4005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe ser menor que {1}.
        /// </summary>
        public static string _4006 {
            get {
                return ResourceManager.GetString("4006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe tener una longitud máxima de {1} caracteres.
        /// </summary>
        public static string _4007 {
            get {
                return ResourceManager.GetString("4007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no está en el formato correcto.
        /// </summary>
        public static string _4008 {
            get {
                return ResourceManager.GetString("4008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad de ordenamiento {0} no pertenece a la clase {1}.
        /// </summary>
        public static string _4009 {
            get {
                return ResourceManager.GetString("4009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se puede enviar ordenamiento por asc o desc.
        /// </summary>
        public static string _4010 {
            get {
                return ResourceManager.GetString("4010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos para consumir el servicio o el token es incorrecto.
        /// </summary>
        public static string _4999 {
            get {
                return ResourceManager.GetString("4999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error interno del servidor.
        /// </summary>
        public static string _5000 {
            get {
                return ResourceManager.GetString("5000", resourceCulture);
            }
        }
    }
}
